In [7]:
1+1

2

In [8]:
import torch as nn

In [9]:
a = nn.Tensor([[1,2], [3,4], [4,5]])

In [10]:
a

tensor([[1., 2.],
        [3., 4.],
        [4., 5.]])

In [11]:
a.type()             

'torch.FloatTensor'

In [12]:
b = nn.Tensor([[1,2.0], [3,4], [4,5]])

In [13]:
b

tensor([[1., 2.],
        [3., 4.],
        [4., 5.]])

In [14]:
b.type()

'torch.FloatTensor'

In [15]:
n_a = a.numpy()

In [16]:
n_a

array([[1., 2.],
       [3., 4.],
       [4., 5.]], dtype=float32)

In [18]:
type(n_a)

numpy.ndarray

In [19]:
a.size()

torch.Size([3, 2])

In [20]:
a.shape

torch.Size([3, 2])

In [21]:
import numpy

In [22]:
e = numpy.array([[1,2], [3,4]])

In [24]:
e

array([[1, 2],
       [3, 4]])

In [25]:
t_e = nn.from_numpy(e)

In [26]:
t_e

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [29]:
float_t_e = t_e.float()
float_t_e

tensor([[1., 2.],
        [3., 4.]])

In [31]:
double_t_e = t_e.double()
double_t_e

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [32]:
if nn.cuda.is_available():
    a_cuda = a.cuda()
    print(a_cuda)

tensor([[1., 2.],
        [3., 4.],
        [4., 5.]], device='cuda:0')


In [33]:
from torch.autograd import *

In [180]:
x = nn.tensor([1.], requires_grad=True)

In [181]:
x

tensor([1.], requires_grad=True)

In [182]:
x.type()

'torch.FloatTensor'

In [61]:
x1 = Variable(nn.Tensor([1]), requires_grad=True)

In [62]:
x1

tensor([1.], requires_grad=True)

In [63]:
x1.type()

'torch.FloatTensor'

In [192]:
w = Variable(nn.Tensor([3]), requires_grad=True)

In [193]:
b = Variable(nn.Tensor([4]), requires_grad=True)

In [194]:
y = w*x + b

In [195]:
# 梯度清零

In [205]:
# y.backward(retain_graph=True)  # 保存前向传播buffer

In [211]:
y.backward()  # y.backward(nn.FloatTensor([1]))

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [209]:
x.data

tensor([1.])

In [210]:
x.grad

tensor([18.])

In [88]:
print(x.grad_fn)

None


In [100]:
a = nn.Tensor(3,2)

In [101]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [99]:
nn.randn(3,2)

tensor([[-1.0194, -1.5639],
        [ 0.0577, -0.5152],
        [ 0.3185,  0.8225]])

In [102]:
c = nn.randn(1,3)

In [103]:
c

tensor([[ 1.4141,  0.3700, -2.0832]])

In [106]:
c.size()

torch.Size([1, 3])

In [107]:
c[0]

tensor([ 1.4141,  0.3700, -2.0832])

In [108]:
c[0,0]

tensor(1.4141)

In [109]:
d = nn.Tensor(3,1)

In [113]:
d

tensor([[-2.0156e+00],
        [ 2.0104e+00],
        [ 1.1210e-44]])

In [143]:
x = nn.ones(1, requires_grad=True)

In [144]:
w = nn.ones(1, requires_grad=True)

In [145]:
y = nn.ones(1, requires_grad=True) 

In [146]:
z = 2*x + 3*y

In [147]:
z

tensor([5.], grad_fn=<AddBackward0>)

In [148]:
total = w + 2*z

In [149]:
total

tensor([11.], grad_fn=<AddBackward0>)

In [150]:
total.backward()

In [151]:
x.grad

tensor([4.])

In [152]:
y.grad

tensor([6.])

In [153]:
w.grad

tensor([1.])

In [154]:
z.grad

C:\Users\LouJH\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


In [173]:
f = nn.ones((2,3), requires_grad=True)

In [174]:
f

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [175]:
f.data

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [176]:
f.data.sub(1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [177]:
f

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [178]:
f.data.sub_(1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [179]:
f

tensor([[0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)